---
- name: Install calico and tigera operator
  command: "{{ item }}"
  loop:
    - kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml
    - kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/custom-resources.yaml
  become: true
  become_user: vagrant
