---
- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - apparmor

- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

#- name: Add apt repository for stable version
#  apt_repository:
#    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
#    state: present

- name: Install docker and its dependecies
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - containerd

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Enable br_netfilter and overlay kernel modules
  command: "{{ item }}"
  loop:
    - modprobe overlay
    - modprobe br_netfilter

- name: enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes

- name: Make /srv/kube directory
  file:
    path: /srv/kube
    state: directory

- name: Install python3-pip
  apt:
    name: python3-pip 

- name: Install python kubernetes client for ansible k8s module 
  pip:
    name: kubernetes
